- project/FrontendBuild.scala
> DDCNLS-1116: Upgrade Play UI to 7.2.1

- project/build.properties
DDCNLS-1415: Upgraded sbt version to 0.13.15
> DDCNLS-1415: Upgraded sbt version to 0.13.15

- conf/messages
@nehakannaujia - only one message deleted; tidying of the headings so that they're consistent with other services; tests didn't fail
> DDCNLS-1612: Refactor message file and slight tidy of headings

- app/views/home/costOfGoods.scala.html
- app/views/home/turnover.scala.html
- app/views/home/vatReturnPeriod.scala.html
- conf/application.conf
- project/FrontendBuild.scala
Updated Assets Frontend Version to 3.0.2, bootstrap to 8.14.0, and added twirl if statements to page errors to stop them appearing whilst no errors are occurring.
> Assets upgrade

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
**New feature**
This is the new PR Checklist that the team agreed they wanted. As a result of this merge, new PRs should automatically add the template into the description which can then be updated by the developer with the relevant information for the reviewer.
> Added new checklist

- .github/CONTRIBUTING.md
- README.md
**Bug fix**
The Download widget in the main README.md file was configured incorrectly, updated to display as intended.
The new contributing guidance referenced the wrong repository and has also been corrected.
> #63 Amended .md file errors

- app/config/frontendAppConfig.scala
- app/controllers/FeedbackSurveyController.scala
- app/views/home/result.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- test/controllers/FeedbackSurveyControllerSpec.scala
- test/helpers/ControllerTestSpec.scala
- test/helpers/ViewSpecHelpers/ResultViewMessages.scala
- test/routes/RoutesSpec.scala
- test/views/home/resultViewSpec.scala
> Implementation of Exit survey and tests

- project/FrontendBuild.scala
> Dependency updates for build

- app/config/frontendAppConfig.scala
- app/config/frontendGlobal.scala
- app/config/frontendWiring.scala
- app/connectors/KeystoreConnector.scala
- app/views/home/vatReturnPeriod.scala.html
- project/FrontendBuild.scala
- project/plugins.sbt
dependVFRfe - update dependencies and plugins tto latest
**Maintenance
Update dependencies and plugins to latest versions as per catalogue
> dependVFRfe updating dependencies and plugins to latest versions

- app/config/frontendWiring.scala
- project/FrontendBuild.scala
- project/plugins.sbt
DL-1471
Play upgrade to support security
> Play upgrade to support security fix

- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
> DL-3585 Updating dependencies

- app/config/VFRSErrorHandler.scala
- conf/messages
- project/AppDependencies.scala
> DL-2574 Update to live services generic 500 error message.

- conf/application.conf
DL-4132
Moving CSRF bypass from app config.
- []  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
> DL-4132 Removing CSRF bypass

- conf/application.conf
- project/AppDependencies.scala
> DL-4236 A11y statement functionality for VATFRS

- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/controllers/CostOfGoodsControllerSpec.scala
- test/controllers/ResultControllerSpec.scala
- test/controllers/TurnoverControllerSpec.scala
- test/controllers/VatReturnPeriodControllerSpec.scala
> DL-5869 Play 2.8 upgrade

- .gitignore
- app/config/VFRSErrorHandler.scala
- app/controllers/CostOfGoodsController.scala
- app/controllers/ResultController.scala
- app/controllers/TimeoutController.scala
- app/controllers/TurnoverController.scala
- app/controllers/VatReturnPeriodController.scala
- app/models/UIHelpersWrapper.scala
- app/views/error_template.scala.html
- app/views/errors/technicalError.scala.html
- app/views/fallback/timeout.scala.html
- app/views/govuk_wrapper.scala.html
- app/views/helpers/moneyInputFormat.scala.html
- app/views/helpers/two_thirds_banner.scala.html
- app/views/helpers/two_thirds_banner_content_ur.scala.html
- app/views/home/costOfGoods.scala.html
- app/views/home/result.scala.html
- app/views/home/turnover.scala.html
- app/views/home/vatReturnPeriod.scala.html
- app/views/main_template.scala.html
- test/controllers/CostOfGoodsControllerSpec.scala
- test/controllers/ResultControllerSpec.scala
- test/controllers/TimeoutControllerSpec.scala
- test/controllers/TurnoverControllerSpec.scala
- test/controllers/VatReturnPeriodControllerSpec.scala
- test/helpers/ControllerTestSpec.scala
- test/views/home/costOfGoodsViewSpec.scala
- test/views/home/resultViewSpec.scala
- test/views/home/turnoverViewSpec.scala
- test/views/home/vatReturnPeriodViewSpec.scala
Moved play-ui components to the templates
> DL-6792 - Changed templates to use DI

- app/views/fallback/timeout.scala.html
> DL-6771 migrate timeout page

- .gitignore
- app/views/helpers/newMoneyInputFormat.scala.html
- app/views/home/turnover.scala.html
- test/controllers/TurnoverControllerSpec.scala
- test/helpers/ViewSpecHelpers/TurnoverViewMessages.scala
- test/views/home/turnoverViewSpec.scala
> DL-6768 - turnover page UI migration

- app/views/Layout.scala.html
- app/views/error_template.scala.html
- test/controllers/ResultControllerSpec.scala
- test/controllers/TimeoutControllerSpec.scala
- test/helpers/ViewSpecHelpers/ResultViewMessages.scala
> DL-6772 error_template.scala.html ui migration

- app/views/home/costOfGoods.scala.html
- test/controllers/CostOfGoodsControllerSpec.scala
- test/helpers/ViewSpecHelpers/CostOfGoodsViewMessages.scala
- test/views/home/costOfGoodsViewSpec.scala
> DL-6769 costOfGoods.scala.html ui migration

- app/views/home/vatReturnPeriod.scala.html
- test/controllers/VatReturnPeriodControllerSpec.scala
- test/helpers/ViewSpecHelpers/VatReturnPeriodViewMessages.scala
- test/views/home/vatReturnPeriodViewSpec.scala
> DL-6767 vatReturnPeriod.scala.html

- app/views/home/costOfGoods.scala.html
- app/views/home/turnover.scala.html
- app/views/home/vatReturnPeriod.scala.html
> DL-6297 - added an ID for continue button

- app/controllers/CostOfGoodsController.scala
- app/controllers/ResultController.scala
- app/controllers/TurnoverController.scala
- app/controllers/VatReturnPeriodController.scala
- app/controllers/predicates/ValidatedSession.scala
- app/views/Layout.scala.html
- app/views/error_template.scala.html
- app/views/errors/technicalError.scala.html
- app/views/fallback/timeout.scala.html
- app/views/helpers/moneyInputFormat.scala.html
- app/views/helpers/newMoneyInputFormat.scala.html
- app/views/home/costOfGoods.scala.html
- app/views/home/result.scala.html
- app/views/home/turnover.scala.html
- app/views/home/vatReturnPeriod.scala.html
- app/views/playComponents/back_link.scala.html
- app/views/playComponents/input_number.scala.html
- conf/application.conf
- conf/prod.routes
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/CostOfGoodsControllerSpec.scala
- test/controllers/ResultControllerSpec.scala
- test/controllers/TurnoverControllerSpec.scala
- test/controllers/VatReturnPeriodControllerSpec.scala
- test/helpers/ControllerTestSpec.scala
- test/routes/RoutesSpec.scala
- test/views/home/costOfGoodsViewSpec.scala
- test/views/home/turnoverViewSpec.scala
- test/views/home/vatReturnPeriodViewSpec.scala
> DL-7869 - Updated play/bootstrap version

- conf/app.routes
> DL-9985 Java11

- app/connectors/DataCacheConnector.scala
- app/controllers/CostOfGoodsController.scala
- app/controllers/ResultController.scala
- app/controllers/TurnoverController.scala
- app/controllers/VatReturnPeriodController.scala
- app/controllers/actions/ValidatedSession.scala
- app/repositories/SessionRepository.scala
- app/utils/CascadeUpsert.scala
- build.sbt
- conf/logback.xml
- project/AppDependencies.scala
- test/connectors/DataCacheConnectorSpec.scala
- test/connectors/FakeDataCacheConnector.scala
- test/controllers/actions/DataRetrievalActionSpec.scala
- test/controllers/actions/FakeDataRetrievalAction.scala
- test/controllers/actions/ValidatedSessionSpec.scala
- test/helpers/ControllerSpecBase.scala
- test/helpers/SpecBase.scala
- test/repositories/SessionRepositorySpec.scala
- test/routes/RoutesSpec.scala
- test/utils/CascadeUpsertSpec.scala
- test/utils/InputOptionSpec.scala
- test/utils/MapFormatsSpec.scala
DL-10560
- Improving test coverage (now >90%)
- Removing Joda time
- Removing unused code
- Dependency updates
> DL-10560 Improve test coverage

- app/views/fallback/timeout.scala.html
- conf/messages
> DL-10595 Updating timeout page content

- app/views/home/costOfGoods.scala.html
- app/views/home/turnover.scala.html
- app/views/home/vatReturnPeriod.scala.html
- conf/application.conf
- conf/messages
- test/helpers/ViewSpecHelpers/CostOfGoodsViewMessages.scala
- test/helpers/ViewSpecHelpers/TurnoverViewMessages.scala
- test/helpers/ViewSpecHelpers/VatReturnPeriodViewMessages.scala
- test/views/home/costOfGoodsViewSpec.scala
- test/views/home/turnoverViewSpec.scala
> DL-10860 update title as per standard

- app/views/home/result.scala.html
- test/helpers/ViewSpecHelpers/ResultViewMessages.scala
- test/views/home/resultViewSpec.scala
> DL-10949 updated inset-text class

- app/views/home/costOfGoods.scala.html
- app/views/home/turnover.scala.html
- conf/messages
- test/controllers/CostOfGoodsControllerSpec.scala
- test/controllers/TurnoverControllerSpec.scala
- test/helpers/ViewSpecHelpers/CostOfGoodsViewMessages.scala
- test/helpers/ViewSpecHelpers/TurnoverViewMessages.scala
- test/views/home/costOfGoodsViewSpec.scala
- test/views/home/turnoverViewSpec.scala
> DL-10862 Updating headings/titles for turnover and costOfGoods pages

- app/connectors/DataCacheConnector.scala
- app/repositories/SessionRepository.scala
- app/utils/CacheMap.scala
- app/utils/CascadeUpsert.scala
- app/utils/KeyStoreEntryValidationException.scala
- project/AppDependencies.scala
- test/connectors/DataCacheConnectorSpec.scala
- test/connectors/FakeDataCacheConnector.scala
- test/controllers/CostOfGoodsControllerSpec.scala
- test/controllers/ResultControllerSpec.scala
- test/controllers/TurnoverControllerSpec.scala
- test/controllers/VatReturnPeriodControllerSpec.scala
- test/controllers/actions/DataRetrievalActionSpec.scala
- test/controllers/actions/FakeDataRetrievalAction.scala
- test/helpers/ControllerSpecBase.scala
- test/repositories/SessionRepositorySpec.scala
- test/utils/CascadeUpsertSpec.scala
> DL-11462 Removing http-caching-client

- app/views/Layout.scala.html
> DL-11947 Convert layout to use hmrcStandardPage

- app/views/Layout.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
> DL-12130 update welsh translation

- project/AppDependencies.scala
> DL-12981 update crown logo

- project/AppDependencies.scala
DL-15305:Rectifying the bobby violation
> DL-15305:Rectifying the bobby violation

- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
DL-15874: Upgrade the dependencies version to the latest.
> DL-15874: Upgrade the dependencies version to the latest.

- project/AppDependencies.scala
- project/plugins.sbt
DL-16923: rectify bobby violations
> DL-16923: rectify bobby violations
